<a href="https://colab.research.google.com/github/dhruvratra9/Student-Management/blob/master/Internship_Project_YBI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Library

In [27]:
import pandas as pd

In [28]:
import numpy as np

Import Dataframe

In [29]:
df = pd.read_csv('https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Placement.csv')

Get the First Five Rows of Dataframe

In [30]:
df.head()

Student_ID  CGPA   IQ  Placement
0           1   6.8  123          1
1           2   5.9  106          0
2           3   5.3  121          0
3           4   7.4  132          1
4           5   5.8  142          0

Get information of Dataframe

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Student_ID  100 non-null    int64  
 1   CGPA        100 non-null    float64
 2   IQ          100 non-null    int64  
 3   Placement   100 non-null    int64  
dtypes: float64(1), int64(3)
memory usage: 3.3 KB


Get the Summary Statistics

In [ ]:
df.describe()

Student_ID        CGPA          IQ   Placement
count  100.000000  100.000000  100.000000  100.000000
mean    50.500000    5.991000  123.580000    0.500000
std     29.011492    1.143634   39.944198    0.502519
min      1.000000    3.300000   37.000000    0.000000
25%     25.750000    5.075000  101.500000    0.000000
50%     50.500000    6.000000  127.500000    0.500000
75%     75.250000    6.900000  149.000000    1.000000
max    100.000000    8.500000  233.000000    1.000000

Get Column Names

In [ ]:
df.columns

Index(['Student_ID', 'CGPA', 'IQ', 'Placement'], dtype='object')

Get Shape of DataFrame

In [ ]:
df.shape

(100, 4)

Get Unique Values (Class or Label) in y Variable

In [ ]:
df['Placement'].value_counts()

Placement
1    50
0    50
Name: count, dtype: int64

In [ ]:
df.groupby('Placement').mean()

Student_ID   CGPA      IQ
Placement                           
0               46.32  5.056  126.88
1               54.68  6.926  120.28

Define y (dependent or label or target variable) and X (independent or features or attribute Variable)

In [32]:
y = df['Placement']

In [33]:
y.shape

(100,)

In [34]:
y

0     1
1     0
2     0
3     1
4     0
     ..
95    0
96    0
97    1
98    1
99    1
Name: Placement, Length: 100, dtype: int64

In [35]:
X = df [['CGPA','IQ']]

or use .drop dunction to define X

In [36]:
X = df.drop(['Student_ID','Placement'], axis=1)

In [37]:
X.shape

(100, 2)

In [38]:
X

CGPA   IQ
0    6.8  123
1    5.9  106
2    5.3  121
3    7.4  132
4    5.8  142
..   ...  ...
95   4.3  200
96   4.4   42
97   6.7  182
98   6.3  103
99   6.2  113

[100 rows x 2 columns]

Get X Variables Standardlized

In [39]:
from sklearn.preprocessing import StandardScaler

In [41]:
ss = StandardScaler()

In [42]:
X = ss.fit_transform(X)

In [43]:
X

array([[ 0.71095807, -0.01459341],
       [-0.0799718 , -0.44233119],
       [-0.60725838, -0.0649155 ],
       [ 1.23824465,  0.21185601],
       [-0.16785289,  0.46346647],
       [ 0.97460136, -1.90167186],
       [-0.25573399,  0.48862751],
       [-0.87090167, -1.52425617],
       [ 0.0957904 ,  0.81572111],
       [-0.78302057, -1.44877303],
       [ 0.0079093 , -1.977155  ],
       [ 0.79883917,  0.36282228],
       [-0.51937728,  0.38798333],
       [ 0.35943369, -0.19072073],
       [ 0.0957904 , -0.51781433],
       [-0.78302057,  1.31894203],
       [-0.69513948,  2.52667224],
       [-2.36488031,  1.49506935],
       [-1.74971264, -0.59329747],
       [-0.69513948,  0.21185601],
       [ 0.53519588, -0.09007654],
       [ 0.97460136,  0.68991588],
       [-0.95878277, -0.09007654],
       [-1.13454496, -0.92039106],
       [-1.13454496, -0.0649155 ],
       [-0.87090167, -0.81974688],
       [ 0.88672027,  1.89764609],
       [ 0.0079093 ,  0.01056764],
       [-0.69513948,

In [44]:
X.shape

(100, 2)

Get Train Test Split

In [45]:
from sklearn.model_selection import train_test_split

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, stratify= y, random_state=2529)

In [49]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((70, 2), (30, 2), (70,), (30,))

Get Model Train

In [50]:
from sklearn.linear_model import LogisticRegression

In [57]:
lr = LogisticRegression()

In [59]:
lr.fit(X_train, y_train)

LogisticRegression()

Get Model Prediction

In [60]:
y_pred = lr.predict(X_test)

In [61]:
y_pred.shape

(30,)

In [62]:
y_pred

array([1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1])

Get Probability of Each Predicted Class

In [63]:
lr.predict_proba(X_test)

array([[0.08483859, 0.91516141],
       [0.94783598, 0.05216402],
       [0.82428598, 0.17571402],
       [0.11224737, 0.88775263],
       [0.45052115, 0.54947885],
       [0.96303907, 0.03696093],
       [0.1221268 , 0.8778732 ],
       [0.0914012 , 0.9085988 ],
       [0.89285662, 0.10714338],
       [0.20301922, 0.79698078],
       [0.96278009, 0.03721991],
       [0.95626777, 0.04373223],
       [0.42699774, 0.57300226],
       [0.3080173 , 0.6919827 ],
       [0.00317841, 0.99682159],
       [0.95705985, 0.04294015],
       [0.00162336, 0.99837664],
       [0.06224347, 0.93775653],
       [0.95870804, 0.04129196],
       [0.10522504, 0.89477496],
       [0.00498911, 0.99501089],
       [0.83589914, 0.16410086],
       [0.97986417, 0.02013583],
       [0.91409766, 0.08590234],
       [0.96348203, 0.03651797],
       [0.32584505, 0.67415495],
       [0.01668451, 0.98331549],
       [0.97616009, 0.02383991],
       [0.93458047, 0.06541953],
       [0.17083607, 0.82916393]])

Get Model Evaluation

In [64]:
from sklearn.metrics import confusion_matrix, classification_report

In [65]:
print(confusion_matrix(y_test, y_pred))

[[14  1]
 [ 0 15]]


In [66]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.93      0.97        15
           1       0.94      1.00      0.97        15

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



Get Future Predictions

Lets select a random sample from existing dataset as new value

Steps to follow

1. Extract a random row using sample function
2. Seprate X and y
3. Standardize X
4. Predict

In [67]:
X_new = df.sample(1)

In [68]:
X_new

Student_ID  CGPA   IQ  Placement
30          31   7.6  128          1

In [69]:
X_new.shape

(1, 4)

In [70]:
X_new = X_new.drop(['Student_ID', 'Placement'], axis = 1)

In [71]:
X_new

CGPA   IQ
30   7.6  128

In [72]:
X_new.shape

(1, 2)

In [74]:
X_new = ss.fit_transform(X_new)

In [75]:
y_pred_new = lr.predict(X_new)

In [76]:
y_pred_new

array([0])

In [78]:
lr.predict_proba(X_new)

array([[0.51362883, 0.48637117]])